export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'


export const TODO_ITEM_REQUEST = 'TODO_ITEM_REQUEST'
export const TODO_ITEM_SUCCESS = 'TODO_ITEM_SUCCESS'
export const TODO_ITEM_FAIL = 'TODO_ITEM_FAIL'



export const  USER_LOGOUT= 'USER_LOGOUT'




export const TODO_ITEM_DELETE_REQUEST = 'TODO_ITEM_DELETE_REQUEST'
export const TODO_ITEM_DELETE_SUCCESS = 'TODO_ITEM_DELETE_SUCCESS'
export const TODO_ITEM_DELETE_FAIL = 'TODO_ITEM_DELETE_FAIL'



export const TODO_STATUS_UPDATE_REQUEST = 'TODO_STATUS_UPDATE_REQUEST'
export const TODO_STATUS_UPDATE_SUCCESS = 'TODO_STATUS_UPDATE_SUCCESS'
export const TODO_STATUS_UPDATE_FAIL = 'TODO_STATUS_UPDATE_FAIL'






export const ADD_TASK_ITEM_REQUEST = 'ADD_TASK_ITEM_REQUEST'
export const ADD_TASK_ITEM_SUCCESS = 'ADD_TASK_ITEM_SUCCESS'
export const ADD_TASK_ITEM_FAIL = 'ADD_TASK_ITEM_FAIL'







export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'






